[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold = { family = "Fira Code Nerd Font", style = "Bold" }
italic = { family = "Fira Code Nerd Font", style = "Italic" }
size = 12
